/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package himes_industries.cameraclient;

import himes_industries.cameraclient.util.*;
import javax.swing.ImageIcon;

/**
 *
 * @author Rich
 */
public class CameraClientFrame extends javax.swing.JFrame {

    private final static String START = "Start";
    private final static String STOP = "Stop";
    
    /**
     * Creates new form CameraClientFrame
     */
    public CameraClientFrame() {
        initComponents();
        getRootPane().setDefaultButton(SendButton);
        Talk.frame = this;
        if (Talk.getBuffer() == null)
            btnSave.setEnabled(false);
        
        /*
        The below line is to show that a received picture can be displayed on the label.
        The /image/#############.jpg is a result the output copied/pasted from Talk.getFilename() 
        on line 132, replace the argument below in quotes with previously created file to prove 
        the image can be displayed in the jLabel (it needs to be sized down somehow).
        */
        
//        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/image/1431276898692.jpg"));
//        lblPicture.setIcon(imageIcon);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ResponseText = new javax.swing.JTextField();
        SendButton = new javax.swing.JButton();
        RequestText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblPicture = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        btnStartStop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Request");

        SendButton.setLabel("Send");
        SendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendButtonActionPerformed(evt);
            }
        });

        RequestText.setText("snap");

        jLabel2.setText("Response");

        lblPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnSave.setText("Save Picture");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnOpen.setText("Open");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        btnStartStop.setText("Start");
        btnStartStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPicture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RequestText, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SendButton))
                                    .addComponent(ResponseText, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(btnSave)
                                .addGap(38, 38, 38)
                                .addComponent(btnOpen))
                            .addComponent(btnStartStop))
                        .addGap(0, 212, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(SendButton)
                    .addComponent(RequestText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResponseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStartStop)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSave)
                        .addComponent(btnOpen)))
                .addGap(47, 47, 47)
                .addComponent(lblPicture, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );

        ResponseText.getAccessibleContext().setAccessibleName("ResponseText");
        ResponseText.getAccessibleContext().setAccessibleDescription("");
        SendButton.getAccessibleContext().setAccessibleName("SendButton");
        SendButton.getAccessibleContext().setAccessibleDescription("");
        RequestText.getAccessibleContext().setAccessibleName("RequestText");
        RequestText.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendButtonActionPerformed
        ResponseText.setText("Waiting");
        ResponseText.setText(Talk.sendMessage(RequestText.getText()));        

//        synchronized(sync){
//            try{Talk.sync.wait(5000);}catch(Exception ex){}
//        }
        
        //Instead of reading from the file, display directly from the byte array.
        byte[] bytes = Talk.getBuffer();
        ImageIcon icon = new ImageIcon(bytes);
        lblPicture.setIcon(ResizeImage.resize(icon));
        btnSave.setEnabled(true);
    }//GEN-LAST:event_SendButtonActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            Talk.saveFile();
        } catch (Exception ex) {}
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        try {
            Talk.openFile();
            ImageIcon icon = new ImageIcon(Talk.getBuffer()); //open jpg file
            //ImageIcon icon = new ImageIcon(Talk.getDecodedBuffer()); //open "b64" file
            lblPicture.setIcon(ResizeImage.resize(icon));
        } catch (Exception ex) {}
        btnSave.setEnabled(true);
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnStartStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartStopActionPerformed
        if(btnStartStop.getText().equals(START)){
            btnStartStop.setText(STOP);
            Talk.start();
        }
        else{
            btnStartStop.setText(START);
            Talk.stop();
        }
    }//GEN-LAST:event_btnStartStopActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CameraClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CameraClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CameraClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CameraClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CameraClientFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RequestText;
    private javax.swing.JTextField ResponseText;
    private javax.swing.JButton SendButton;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnStartStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblPicture;
    // End of variables declaration//GEN-END:variables

public javax.swing.JLabel getLblPicture(){
    return lblPicture;
}
}
